### ISSUE TITLE
Mailinator email support is {{t "no bueno"}}

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-mailer#29]
From @pdehaan in https://github.com/mozilla/fxa-content-server/issues/1053

---------------------------

Found in https://accounts.stage.mozaws.net/ver.json (commit 04f143ea4e6d53eb6d7453c3ccf7ec3ca9bb2d24)

```json
{"version":"0.11.2","commit":"04f143ea4e6d53eb6d7453c3ccf7ec3ca9bb2d24"}
```

---

### Steps to reproduce:
1. Create a new account and set it to a mailinator.com email.
2. Try and verify your email.

### Actual results:
Sadness.

![_2__mailinator_-_free__disposable__email_](https://cloud.githubusercontent.com/assets/557895/2867326/ebeb008c-d234-11e3-9e04-fceae080fd2c.png)

### Expected results:
Happiness.

### Workaround:
Select all the text. The "Verify" text appears. White on white, bro.

![_2__mailinator_-_free__disposable__email_](https://cloud.githubusercontent.com/assets/557895/2867330/0632344c-d235-11e3-8623-8bf62658aaa3.png)

**Comment by johngruen** [comment]
Should be fixed by: https://github.com/mozilla/fxa-auth-mailer/issues/35

**Comment by vladikoff** [comment]
Still an issue: 
![image](https://cloud.githubusercontent.com/assets/128755/8826845/3ce39522-3057-11e5-8946-4da5c2f2571d.png)

**Comment by vladikoff** [comment]
Should be fixed via https://github.com/mozilla/fxa-auth-mailer/commit/b8f5480703945ec26f72952adc9cc60ff9d71d82#diff-20ee765c36edf392537bf74d8d8d3d84R54
